name: lucky-website

services:
  remix-prod:
    container_name: remix-prod
    build:
      context: .
      dockerfile: ./Dockerfile.yarn
    ports:
      - 3003:3003
    environment:
      - NODE_ENV=production
      - PORT=3003

  caddy-prod:
    build:
      context: .
      dockerfile: ./Dockerfile.caddy
    container_name: caddy-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      - ./.env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
  caddy_config:
